# 软件版本，对应安装包名称版本
docker_version: '18.09.6'
etcd_version: '3.3.13'
flannel_version: '0.11.0'
k8s_version: '1.16'

# 安装目录 
k8s_work_dir: '/opt/kubernetes'
etcd_work_dir: '/opt/etcd'
tmp_dir: '/tmp/k8s'

# 容器网络
service_cidr: '10.0.0.0/24'
cluster_dns: '10.0.0.2'
pod_cidr: '172.17.0.0/16'
service_nodeport_range: '30000-32767'
cluster_domain: 'cluster.local'

# 高可用
vip: '192.168.31.88'
nic: 'ens33' 

# 自签证书可信任IP列表，为方便扩展，可添加多个预留IP
cert_hosts:
  # 包含所有LB、VIP和Master IP
  k8s:
    - 192.168.31.61
    - 192.168.31.62
    - 192.168.31.63
    - 192.168.31.71
    - 192.168.31.72
    - 192.168.31.73
    - 192.168.31.88
  # 包含所有etcd节点IP
  etcd:
    - 192.168.31.61
    - 192.168.31.62
    - 192.168.31.63
