---
- name: 创建工作目录
  file: dest={{ k8s_work_dir }}/{{ item }} state=directory
  with_items:
    - bin
    - cfg
    - ssl
    - logs

- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: 拷贝二进制包
  copy: src=master-binary.tar.gz dest={{ tmp_dir }}

- name: 移动二进制包
  shell: cd {{ tmp_dir }} && \
         tar zxf master-binary.tar.gz && \
         cp -rf kube-apiserver kube-controller-manager kube-scheduler {{ k8s_work_dir }}/bin && \
         mv kubectl /usr/bin && \
         chmod +x /usr/bin/kubectl {{ k8s_work_dir }}/bin/*

- name: 拷贝k8s证书
  copy: src=k8s_cert/{{ item }} dest={{ k8s_work_dir }}/ssl
  with_items:
    - ca.pem
    - ca-key.pem
    - server.pem
    - server-key.pem

- name: 拷贝etcd证书
  copy: src=etcd_cert/{{ item }} dest={{ etcd_work_dir }}/ssl
  with_items:
    - ca.pem
    - server.pem
    - server-key.pem

- name: 拷贝token文件
  copy: src=token.csv dest={{ k8s_work_dir }}/cfg

- name: 拷贝k8s配置文件
  template: src={{ item }} dest={{ k8s_work_dir }}/cfg/{{ item.split('.')[:-1]|join('.') }}
  with_items:
    - kube-apiserver.conf.j2
    - kube-controller-manager.conf.j2
    - kube-scheduler.conf.j2
  notify:
    - restart kube-apiserver 
    - restart kube-controller-manager
    - restart kube-scheduler 

- name: 拷贝service文件
  template: src={{ item }} dest=/usr/lib/systemd/system/{{ item.split('.')[:-1]|join('.') }}
  with_items:
    - kube-apiserver.service.j2
    - kube-controller-manager.service.j2
    - kube-scheduler.service.j2
  notify:
    - reload systemd
    - restart kube-apiserver 
    - restart kube-controller-manager
    - restart kube-scheduler 

- name: 启动k8s master
  service: name={{ item }} state=started enabled=yes
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: 查看集群状态
  shell: sleep 3 && kubectl get cs
  register: cs
- debug: var=cs.stdout_lines

- name: 拷贝RBAC文件
  copy: src={{ item }} dest={{ tmp_dir }}
  with_items:
    - kubelet-bootstrap-rbac.yaml
    - apiserver-to-kubelet-rbac.yaml

- name: 授权APIServer访问Kubelet与授权kubelet bootstrap
  shell: kubectl apply -f {{ tmp_dir }}/apiserver-to-kubelet-rbac.yaml && \
         kubectl apply -f {{ tmp_dir }}/kubelet-bootstrap-rbac.yaml

